version: "2"

linters:
  default: standard
  enable:
    - errorlint
    - gocritic
    - misspell
    - unconvert
    - unparam

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
